/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Altree__factory } from "./Altree__factory";
export { AltreeFactory__factory } from "./AltreeFactory__factory";
