/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface AltreeFactoryInterface extends utils.Interface {
  functions: {
    "createRoute(address,address,string,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createRoute"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createRoute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createRoute",
    data: BytesLike
  ): Result;

  events: {
    "NewRoute(address,address,address,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewRoute"): EventFragment;
}

export interface NewRouteEventObject {
  route: string;
  user: string;
  beneficiary: string;
  name: string;
  tax: BigNumber;
}
export type NewRouteEvent = TypedEvent<
  [string, string, string, string, BigNumber],
  NewRouteEventObject
>;

export type NewRouteEventFilter = TypedEventFilter<NewRouteEvent>;

export interface AltreeFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AltreeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createRoute(
      user: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      label: PromiseOrValue<string>,
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createRoute(
    user: PromiseOrValue<string>,
    beneficiary: PromiseOrValue<string>,
    label: PromiseOrValue<string>,
    tax: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createRoute(
      user: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      label: PromiseOrValue<string>,
      tax: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "NewRoute(address,address,address,string,uint256)"(
      route?: null,
      user?: null,
      beneficiary?: null,
      name?: null,
      tax?: null
    ): NewRouteEventFilter;
    NewRoute(
      route?: null,
      user?: null,
      beneficiary?: null,
      name?: null,
      tax?: null
    ): NewRouteEventFilter;
  };

  estimateGas: {
    createRoute(
      user: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      label: PromiseOrValue<string>,
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createRoute(
      user: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      label: PromiseOrValue<string>,
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
